networks:
  app_network:

services:
  nginx:
    image: nginx:latest
    container_name: nginx-container
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - cicd-app-blue
      - cicd-app-green
    networks:
      - app_network

  cicd-app-blue:
    container_name: cicd-app-blue
    image: mone921111/cicd-app:latest  # ✅ 공통 최신 이미지 사용
    restart: always
    depends_on:
      - mysql-container
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8081:8080"
    networks:
      - app_network

  cicd-app-green:
    container_name: cicd-app-green
    image: mone921111/cicd-app:latest  # ✅ 공통 최신 이미지 사용
    restart: always
    depends_on:
      - mysql-container
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8082:8080"
    networks:
      - app_network

  mysql-container:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1318
      MYSQL_DATABASE: demo_db
      MYSQL_USER: demo_user
      MYSQL_PASSWORD: 1318
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

volumes:
  mysql_data:
