networks:
  app_network:

services:
  nginx:
    image: nginx:latest
    container_name: nginx-container
    restart: always
    ports:
      - "80:80"  # ✅ 클라이언트 요청을 80번 포트에서 수신
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro  # ✅ Nginx 설정 파일 추가
    depends_on:
      - app  # ✅ Spring Boot가 먼저 실행된 후 Nginx 실행
    networks:
      - app_network

  app:
    container_name: cicd-app
    image: mone921111/cicd-app:latest
    restart: always
    depends_on:
      - mysql-container
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8080:8080"  # ✅ Spring Boot 컨테이너가 내부에서 8080 포트로 실행됨
    networks:
      - app_network

  mysql-container:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1318
      MYSQL_DATABASE: demo_db
      MYSQL_USER: demo_user
      MYSQL_PASSWORD: 1318
    volumes:
      - mysql_data:/var/lib/mysql  # ✅ MySQL 데이터를 영구 저장
    networks:
      - app_network

volumes:
  mysql_data: