services:
  app:
    container_name: cicd-app
    image: mone92111/cicd-app:latest  # ✅ Docker Hub에서 최신 이미지 가져오기
    ports:
      - "80:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - mysql-container  # ✅ MySQL이 먼저 실행되도록 설정
    restart: always

  mysql-container:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1318
      MYSQL_DATABASE: demo_db
      MYSQL_USER: demo_user
      MYSQL_PASSWORD: 1318
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql  # ✅ DB 데이터 유지

volumes:
  mysql_data:
