version: '3.8'

services:
  app:
    container_name: cicd-app
    image: cicd-app:latest
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: always
