# ✅ 로컬 개발 환경에서 사용하는 설정 (주석 처리된 부분)
# spring:
#   datasource:
#     url: jdbc:mysql://localhost:3306/demo_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#     username: demo_user
#     password: 1318
#   jpa:
#     hibernate:
#       ddl-auto: update  # ✅ Hibernate가 DB 스키마를 자동으로 업데이트
#     show-sql: true  # ✅ 실행되는 SQL을 콘솔에 출력

spring:
  datasource:
    url: jdbc:mysql://mysql-container:3306/demo_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: demo_user
    password: 1318
  jpa:
    hibernate:
      ddl-auto: update  # ✅ DB 스키마 자동 업데이트 (운영 환경에서는 'none'으로 설정 추천)
    show-sql: false  # ✅ SQL 로그 출력 여부 (디버깅 시 true로 변경 가능)
    properties:
      hibernate:
        jdbc:
          batch_size: 10  # ✅ JDBC 배치 크기 설정 (데이터 대량 삽입 시 성능 향상)
        generate_statistics: false  # ✅ Hibernate 성능 통계 정보 출력 여부 (디버깅 시 true로 변경 가능)
    open-in-view: false  # ✅ OSIV(Open Session In View) 비활성화 (성능 최적화)
