#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/demo_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#    username: demo_user
#    password: 1318
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true

spring:
  datasource:
    url: jdbc:mysql://mysql-container:3306/demo_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: demo_user
    password: 1318
  jpa:
    hibernate:
      ddl-auto: update    # ??????? none?? ??
    show-sql: false     # ??????? false? ??
    properties:
      hibernate:
        jdbc:
          batch_size: 10  # ?? ??? ??
        generate_statistics: false  # ?? ?? ????
    open-in-view: false  # OSIV ????
